# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18HQ1xG0hYom0OXPT0s_lYQBeJZpUokQR
"""

import pandas as pd
import numpy as np
import requests
import zipfile
import io
from scipy.stats import rankdata
from joblib import Parallel, delayed
import time

# ══════════════════════════════════════════════════════════════
#  STEP 1 — Download TCGA gene expression
# ══════════════════════════════════════════════════════════════
print("=" * 60)
print("STEP 1: Downloading TCGA HiSeqV2...")
print("=" * 60)
t0 = time.time()

url = "https://tcga-xena-hub.s3.us-east-1.amazonaws.com/download/TCGA.BRCA.sampleMap%2FHiSeqV2.gz"
df = pd.read_csv(url, sep="\t", index_col=0, compression="gzip")
df = df.apply(pd.to_numeric, errors="coerce")
df = df.T.fillna(df.median(axis=1)).T
print(f"Loaded : {df.shape[0]} genes × {df.shape[1]} samples")
print(f"Time   : {time.time()-t0:.1f}s")

# ══════════════════════════════════════════════════════════════
#  STEP 2 — Fetch Reactome pathways
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 2: Fetching Reactome pathways...")
print("=" * 60)
t0 = time.time()

reactome_url = "https://reactome.org/download/current/ReactomePathways.gmt.zip"
r = requests.get(reactome_url)
with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    gmt_filename = [f for f in z.namelist() if f.endswith(".gmt")][0]
    gmt_content  = z.read(gmt_filename).decode("utf-8")

gene_sets_raw = {}
for line in gmt_content.strip().split("\n"):
    parts = line.strip().split("\t")
    if len(parts) >= 3:
        gene_sets_raw[parts[0].strip()] = [g.strip() for g in parts[2:] if g.strip()]

gene_sets = {
    name: genes for name, genes in gene_sets_raw.items()
    if 10 <= len(genes) <= 1000
}
print(f"  Total raw Reactome pathways         : {len(gene_sets_raw)}")
print(f"  After size filter (10–1000 genes)   : {len(gene_sets)}")
print(f"Time   : {time.time()-t0:.1f}s")

# ══════════════════════════════════════════════════════════════
#  STEP 3 — Pre-compute gene index & boolean masks
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 3: Pre-computing gene indices & pathway masks...")
print("=" * 60)
t0 = time.time()

genes      = df.index.tolist()
samples    = df.columns.tolist()
n_genes    = len(genes)
n_samples  = len(samples)
gene_index = {g: i for i, g in enumerate(genes)}
expr_genes = set(genes)

expr_arr = df.values.astype(np.float64)

pathway_masks = {}
for name, pw_genes in gene_sets.items():
    overlap = [g for g in pw_genes if g in expr_genes]
    if len(overlap) >= 10:
        mask = np.zeros(n_genes, dtype=bool)
        for g in overlap:
            mask[gene_index[g]] = True
        pathway_masks[name] = mask

print(f"  Pathways with ≥10 overlapping genes : {len(pathway_masks)}")
print(f"  Expression matrix dtype             : float64")
print(f"  Memory                              : {expr_arr.nbytes/1e6:.1f} MB")
print(f"Time   : {time.time()-t0:.1f}s")

# ══════════════════════════════════════════════════════════════
#  STEP 4 — Rank all samples
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 4: Ranking all samples (scipy.rankdata float64)...")
print("=" * 60)
t0 = time.time()

def rank_one_sample(col_idx):
    return rankdata(expr_arr[:, col_idx], method="average")

ranked_cols = Parallel(n_jobs=-1, verbose=0)(
    delayed(rank_one_sample)(s) for s in range(n_samples)
)

ranks        = np.column_stack(ranked_cols)
global_order = np.argsort(ranks, axis=0)[::-1]
sorted_ranks = np.take_along_axis(ranks, global_order, axis=0)

print(f"  Ranking dtype  : {ranks.dtype}")
print(f"  Samples ranked : {n_samples}")
print(f"Time   : {time.time()-t0:.1f}s")
# ══════════════════════════════════════════════════════════════
#  STEP 5 — Vectorised ssGSEA (Barbie et al. 2009 — exact)
# ══════════════════════════════════════════════════════════════
def ssgsea_vectorized(mask, alpha=0.25):
    ranked_mask = mask[global_order]
    in_weights  = np.where(ranked_mask, sorted_ranks ** alpha, 0.0)
    in_sum      = in_weights.sum(axis=0, keepdims=True) + 1e-12
    ecdf_in     = np.cumsum(in_weights, axis=0) / in_sum
    out_count   = (~ranked_mask).sum(axis=0, keepdims=True) + 1e-12
    ecdf_out    = np.cumsum(~ranked_mask, axis=0) / out_count
    return (ecdf_in - ecdf_out).sum(axis=0)

# ══════════════════════════════════════════════════════════════
#  STEP 6 — Score all pathways in parallel batches
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 6: Running ssGSEA across all pathways...")
print("=" * 60)
t0 = time.time()

BATCH_SIZE  = 100
all_results = {}

def score_batch(batch_items):
    return [(name, ssgsea_vectorized(mask)) for name, mask in batch_items]

batches = [
    list(pathway_masks.items())[i : i + BATCH_SIZE]
    for i in range(0, len(pathway_masks), BATCH_SIZE)
]
print(f"  {len(pathway_masks)} pathways → {len(batches)} batches of {BATCH_SIZE}")

batch_results = Parallel(n_jobs=-1, verbose=2)(
    delayed(score_batch)(batch) for batch in batches
)

for batch in batch_results:
    for name, scores in batch:
        all_results[name] = scores

print(f"\n  Pathways scored : {len(all_results)}")
print(f"Time   : {time.time()-t0:.1f}s")

# ══════════════════════════════════════════════════════════════
#  STEP 7 — Build matrix & normalise [0, 1]
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 7: Building & normalising pathway score matrix...")
print("=" * 60)
t0 = time.time()

pathway_df = pd.DataFrame(all_results, index=samples).T
pathway_df.index.name = "pathway"

pathway_df = pathway_df.subtract(pathway_df.min(axis=1), axis=0)
pathway_df = pathway_df.divide(pathway_df.max(axis=1).replace(0, 1), axis=0)

print(f"  Shape : {pathway_df.shape[0]} pathways × {pathway_df.shape[1]} samples")
print(f"  Range : {pathway_df.values.min():.4f} – {pathway_df.values.max():.4f}")
print(f"  dtype : {pathway_df.values.dtype}")

pathway_df.to_csv("tcga_pathway_scores_ssgsea_reactome.csv")
print(f"Saved → tcga_pathway_scores_ssgsea_reactome.csv")
print(f"Time   : {time.time()-t0:.1f}s")

# ══════════════════════════════════════════════════════════════
#  STEP 8 — Download TCGA clinical matrix
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 8: Downloading TCGA clinical matrix...")
print("=" * 60)
t0 = time.time()

clin_url = (
    "https://tcga-xena-hub.s3.us-east-1.amazonaws.com/download/"
    "TCGA.BRCA.sampleMap%2FBRCA_clinicalMatrix"
)
clin_df = pd.read_csv(clin_url, sep="\t", index_col=0, low_memory=False)
print(f"  Shape : {clin_df.shape[0]} samples × {clin_df.shape[1]} columns")
print(f"Time   : {time.time()-t0:.1f}s")

# ══════════════════════════════════════════════════════════════
#  STEP 9 — Build stage column
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 9: Building 8-phase stage column...")
print("=" * 60)

cols     = ["targeted_molecular_therapy", "radiation_therapy",
           "days_to_death", "days_to_last_followup"]
stage_df = clin_df[cols].copy()

# OS time: use days_to_death; fall back to days_to_last_followup if missing
stage_df["os_time"] = pd.to_numeric(stage_df["days_to_death"], errors="coerce")
stage_df["os_time"] = stage_df["os_time"].fillna(
    pd.to_numeric(stage_df["days_to_last_followup"], errors="coerce")
)
stage_df = stage_df.dropna(subset=["targeted_molecular_therapy", "radiation_therapy", "os_time"])
stage_df["tmt_bin"] = stage_df["targeted_molecular_therapy"].str.strip().str.upper().map({"YES": 1, "NO": 0})
stage_df["rt_bin"]  = stage_df["radiation_therapy"].str.strip().str.upper().map({"YES": 1, "NO": 0})
stage_df            = stage_df.dropna(subset=["tmt_bin", "rt_bin"])
stage_df[["tmt_bin","rt_bin"]] = stage_df[["tmt_bin","rt_bin"]].astype(int)
stage_df["os_bin"]  = (stage_df["os_time"] >= 180).astype(int)
stage_df["stage"]   = stage_df["tmt_bin"]*4 + stage_df["rt_bin"]*2 + stage_df["os_bin"]*1
stage_df            = stage_df[["stage"]].copy()
stage_df.index.name = "sample"

print(f"  Samples with valid stage : {len(stage_df)}")
meanings = {
    0:"000 | No TMT  | No RT  | OS < 180d", 1:"001 | No TMT  | No RT  | OS ≥ 180d",
    2:"010 | No TMT  | RT Yes | OS < 180d", 3:"011 | No TMT  | RT Yes | OS ≥ 180d",
    4:"100 | TMT Yes | No RT  | OS < 180d", 5:"101 | TMT Yes | No RT  | OS ≥ 180d",
    6:"110 | TMT Yes | RT Yes | OS < 180d", 7:"111 | TMT Yes | RT Yes | OS ≥ 180d",
}
for s, count in stage_df["stage"].value_counts().sort_index().items():
    print(f"    Stage {s} ({meanings[s]}) : {count}")

# ══════════════════════════════════════════════════════════════
#  STEP 10 — Merge stage + pathway scores
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 10: Merging stage labels with pathway scores...")
print("=" * 60)

pathway_T           = pathway_df.T
pathway_T.index.name = "sample"
common              = set(stage_df.index) & set(pathway_T.index)
combined            = stage_df.join(pathway_T, how="inner")

print(f"  Common samples      : {len(common)}")
print(f"  Final shape         : {combined.shape[0]} samples × {combined.shape[1]} columns")

combined.to_csv("tcga_stage_reactome_scores.csv")
print("Saved → tcga_stage_reactome_scores.csv")

# ══════════════════════════════════════════════════════════════
#  STEP 11 — ROBUST DOWNLOAD (3 methods, fallback chain)
# ══════════════════════════════════════════════════════════════
print("\n" + "=" * 60)
print("STEP 11: Downloading files...")
print("=" * 60)

files_to_download = [
    "tcga_pathway_scores_ssgsea_reactome.csv",
    "tcga_stage_reactome_scores.csv"
]

# ── Method 1: Standard Colab files.download ───────────────────
def method1_colab(filename):
    try:
        from google.colab import files
        files.download(filename)
        print(f"Method 1 success : {filename}")
        return True
    except Exception as e:
        print(f"Method 1 failed  : {e}")
        return False

# ── Method 2: Copy to Google Drive ───────────────────────────
def method2_drive(filename):
    try:
        from google.colab import drive
        drive.mount("/content/drive", force_remount=False)
        import shutil, os
        dest = f"/content/drive/MyDrive/{filename}"
        shutil.copy(filename, dest)
        print(f"Method 2 success : saved to Google Drive → MyDrive/{filename}")
        return True
    except Exception as e:
        print(f"Method 2 failed  : {e}")
        return False

# ── Method 3: Base64 inline download link ────────────────────
def method3_base64(filename):
    try:
        import base64
        from IPython.display import display, HTML
        with open(filename, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        href = (
            f'<a href="data:file/csv;base64,{b64}" '
            f'download="{filename}" '
            f'style="font-size:16px; font-weight:bold; '
            f'background:#4CAF50; color:white; padding:8px 16px; '
            f'border-radius:4px; text-decoration:none;">'
            f'Click to download {filename}</a>'
        )
        display(HTML(href))
        print(f"Method 3 success : click the green button above")
        return True
    except Exception as e:
        print(f"Method 3 failed  : {e}")
        return False
# ── Try each file with fallback chain ────────────────────────
for fname in files_to_download:
    print(f"\n  Downloading: {fname}")
    if not method1_colab(fname):
        print(f"  Trying Google Drive fallback...")
        if not method2_drive(fname):
            print(f"  Trying base64 link fallback...")
            method3_base64(fname)

print("\n" + "=" * 60)
print("ALL DONE!!")
print("=" * 60)