"""LaTeX table writers (booktabs style) used at every pipeline phase.

Tables are wrapped in `\\resizebox{\\linewidth}{!}{...}` so they never overflow
their containing column, and may be emitted either inside a single-column
`table` or a full-width `table*` environment (the latter spans both columns
in `acmart` sigconf layout). Placement is `[!ht]` so the typesetter has the
flexibility to bin-pack many tables without overlap.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence


def _escape(s) -> str:
    """Escape a value for safe insertion into LaTeX cells."""
    if isinstance(s, float):
        s = f"{s:.3f}"
    elif s is None:
        s = ""
    s = str(s)
    return (
        s.replace("\\", r"\textbackslash{}")
         .replace("&", r"\&")
         .replace("%", r"\%")
         .replace("$", r"\$")
         .replace("#", r"\#")
         .replace("_", r"\_")
         .replace("{", r"\{")
         .replace("}", r"\}")
         .replace("^", r"\textasciicircum{}")
         .replace("~", r"\textasciitilde{}")
    )


def booktabs_table(headers: Sequence[str],
                   rows: Sequence[Sequence],
                   caption: str,
                   label: str,
                   align: str | None = None,
                   full_width: bool = False) -> str:
    """Render a booktabs table that is safe for ACM sigconf two-column layout.

    Parameters
    ----------
    full_width
        If True, use the starred `table*` environment so the table spans both
        columns. Recommended for any table with more than 5 logical columns
        or with wide text content (e.g. the per-head metrics table).
    """
    if align is None:
        align = "l" + "r" * (len(headers) - 1)
    head_line = " & ".join(_escape(h) for h in headers) + r" \\"
    body_lines = "\n".join(
        " & ".join(_escape(c) for c in row) + r" \\"
        for row in rows
    )
    env = "table*" if full_width else "table"
    inner_size = r"\small" if full_width else r"\footnotesize"
    return (
        "% Auto-generated by binn.reporting — do not hand-edit.\n"
        f"\\begin{{{env}}}[!ht]\n"
        "\\centering\n"
        f"{inner_size}\n"
        f"\\caption{{{_escape(caption)}}}\n"
        f"\\label{{tab:{label}}}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        f"\\begin{{tabular}}{{{align}}}\n"
        "\\toprule\n"
        f"{head_line}\n"
        "\\midrule\n"
        f"{body_lines}\n"
        "\\bottomrule\n"
        "\\end{tabular}}\n"
        f"\\end{{{env}}}\n"
    )


def write_table(path: Path,
                headers: Sequence[str],
                rows: Sequence[Sequence],
                caption: str,
                label: str,
                align: str | None = None,
                full_width: bool = False) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(booktabs_table(headers, rows, caption, label, align,
                                    full_width=full_width))
    return path
