"""LaTeX table writers (booktabs style) used at every pipeline phase."""
from __future__ import annotations

from pathlib import Path
from typing import Sequence


def _escape(s) -> str:
    """Escape a value for safe insertion into LaTeX cells."""
    if isinstance(s, float):
        # 3 sig figs by default; users can pre-format if they need more.
        s = f"{s:.3f}"
    elif s is None:
        s = ""
    s = str(s)
    return (
        s.replace("\\", r"\textbackslash{}")
         .replace("&", r"\&")
         .replace("%", r"\%")
         .replace("$", r"\$")
         .replace("#", r"\#")
         .replace("_", r"\_")
         .replace("{", r"\{")
         .replace("}", r"\}")
         .replace("^", r"\textasciicircum{}")
         .replace("~", r"\textasciitilde{}")
    )


def booktabs_table(headers: Sequence[str],
                   rows: Sequence[Sequence],
                   caption: str,
                   label: str,
                   align: str | None = None) -> str:
    """Render a booktabs table (no \\usepackage needed beyond `booktabs`)."""
    if align is None:
        align = "l" + "r" * (len(headers) - 1)
    head_line = " & ".join(_escape(h) for h in headers) + r" \\"
    body_lines = "\n".join(
        " & ".join(_escape(c) for c in row) + r" \\"
        for row in rows
    )
    return (
        "% Auto-generated by binn.reporting — do not hand-edit.\n"
        "\\begin{table}[ht]\n"
        "\\centering\n"
        f"\\caption{{{_escape(caption)}}}\n"
        f"\\label{{tab:{label}}}\n"
        f"\\begin{{tabular}}{{{align}}}\n"
        "\\toprule\n"
        f"{head_line}\n"
        "\\midrule\n"
        f"{body_lines}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )


def write_table(path: Path,
                headers: Sequence[str],
                rows: Sequence[Sequence],
                caption: str,
                label: str,
                align: str | None = None) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(booktabs_table(headers, rows, caption, label, align))
    return path
